# Site settings
title: Behind the Change
email: hello@kevinchau.me
description: Behind the Change. People make differences within their own communities everyday. Read their stories.
baseurl: / # the subpath of your site, e.g. /blog/
url: "https://behindthechange.com" # the base hostname & protocol for your site
future: false
permalink: /:categories/:title
custom_paginate: 5
paginate_path: /blog/page:num

# Build settings
markdown: kramdown
permalink: none

gems:
  - jekyll-sitemap

exclude:
  - _assets
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/bundle/**
  - vendor
